language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11
env:
  - STORAGE_TYPE=mariadb
  - STORAGE_TYPE=h2
before_install:
#  - sudo apt-get update
#  # workaround for missing ca certs in openjdk
#  - sudo dpkg --purge --force-depends ca-certificates-java
#  - sudo apt-get install ca-certificates-java
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"

branches:
  only:
    - master
script: mvn compile test
jobs:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - stage: deploy
      jdk: oraclejdk8
      env: STORAGE_TYPE=h2
      deploy:
        provider: script
        script: bash ./.travis/deploy.sh
        on:
          branch: master
