language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
env:
  - STORAGE_TYPE=mariadb
  - STORAGE_TYPE=h2
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
script: mvn compile test
jobs:
  include:
    - jdk: openjdk11
      env: STORAGE_TYPE=mariadb
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk11
      env: STORAGE_TYPE=h2
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - stage: deploy
      jdk: oraclejdk8
      script: skip
      if: branch = master
      deploy:
        provider: script
        script: bash ./.travis/deploy.sh
        on:
          branch: master
