main: me.confuserr.banmanager.BanManager
name: BanManager
version: 3.13
website: http://dev.bukkit.org/bukkit-plugins/ban-management/
authors: [confuserr]
commands: 
  ban: 
    description: "ban a player"
    usage: "/ban <username> <reason>"
    aliases: [bmban]
  banall: 
    description: "ban a player across multiple servers"
    usage: "/banall <username> <reason>"
    aliases: [bmbanall]
  tempban: 
    description: "tempban a player"
    usage: "/tempban <username> <timeDiff> <reason>"
    aliases: [bmtempban]
  tempbanall: 
    description: "tempban a player across multiple servers"
    usage: "/tempbanall <username> <timeDiff> <reason>"
    aliases: [bmtempbanall]
  unban:
    description: "unban a player"
    usage: "/unban <username>"
    aliases: [bmunban]
  unbanall:
    description: "unban a player across multiple servers"
    usage: "/unbanall <username>"
    aliases: [bmunbanall]
  bminfo:
    description: "see information on a player"
    usage: "/bminfo <username>"
    aliases: [bmbminfo]
  banip:
    description: "ban an ip"
    usage: "/banip <username || IP Address> <reason>"
    aliases: [bmbanip]
  banipall:
    description: "ban an ip across multiple servers"
    usage: "/banipall <username || IP Address> <reason>"
    aliases: [bmbanipall]
  tempbanip: 
    description: "tempban an ip"
    usage: "/tempbanip <username || IP Address> <timeDiff> <reason>"
    aliases: [bmtempbanip]
  tempbanipall: 
    description: "tempban an ip across multiple servers"
    usage: "/tempbanipall <username || IP Address> <timeDiff> <reason>"
    aliases: [bmtempbanipall]
  unbanip:
    description: "unban's an ip"
    usage: "/unbanip <IP Address>"
    aliases: [bmunbanip]
  unbanipall:
    description: "unban's an ip across multiple servers"
    usage: "/unbanipall <IP Address>"
    aliases: [bmunbanipall]
  banimport:
    description: "imports bans"
    usage: "/banimport <player || ip> <reason>"
    aliases: [bmbanimport]
  kick:
    description: "kick a player"
    usage: "/kick <player> <reason>"
    aliases: [bmkick]
  mute:
    description: "mutes a player"
    usage: "/mute <player> <reason>"
    aliases: [bmmute]
  muteall:
    description: "mutes a player across multiple servers"
    usage: "/muteall <player> <reason>"
    aliases: [bmmuteall]
  tempmute:
    description: "temp mutes a player"
    usage: "/tempmute <player> <timeDiff> <reason>"
    aliases: [bmtempmute]
  tempmuteall:
    description: "temp mutes a player across multiple servers"
    usage: "/tempmuteall <player> <timeDiff> <reason>"
    aliases: [bmtempmuteall]
  unmute:
    description: "unmute a player"
    usage: "/unmute <username>"
    aliases: [bmunmute]
  unmuteall:
    description: "unmute a player across multiple servers"
    usage: "/unmuteall <username>"
    aliases: [bmunmuteall]
  nlkick:
    description: "kick a player without logging"
    usage: "/nlkick <player> <reason>"
    aliases: [bmnlkick]
  bmreload:
    description: "Reloads from the config everything except database connection info"
    usage: "/bmreload"
  bmtools:
    description: "Collection of random utilities"
    usage: "/bmtools <tool>"
  warn:
    description: "Warn a player"
    usage: "/warn <player> <reason>"
    aliases: [bmwarn]
  bmclear:
    description: "Clear a player's records"
    usage: "/bmclear <type> <player>"
permissions:
    bm.*:
        description: Gives access to all BanManager commands
        children:
            bm.ban: true
            bm.unban: true
            bm.tempban: true
            bm.exempt: true
            bm.bminfo: true
            bm.notify: true
            bm.banip: true
            bm.tempbanip: true
            bm.unbanip: true
            bm.import: true
            bm.kick: true
            bm.update: true
            bm.mute: true
            bm.tempmute: true
            bm.unmute: true
            bm.banoffline: true
            bm.tempbanoffline: true
            bm.warn: true
            bm.clear: true
    bm.unban:
        description: Allows you to unban a user
        default: op
    bm.ban:
        description: Allows you to ban a user
        default: op
    bm.banoffline:
        description: Allows you to ban an offline user
        default: op
    bm.tempban:
        description: Allows you to tempban a user
        default: op
    bm.tempbanoffline:
        description: Allows you to tempban an offline user
        default: op
    bm.exempt:
        description: Prevents this user from being banned or kicked
        default: op
    bm.bminfo:
        description: Allows you to see information on players
        default: op
    bm.notify:
        description: Players with this permission will be told of bans
        default: op
    bm.banip:
        description: Allows you to ban an ip
        default: op
    bm.tempbanip:
        description: Allows you to temban an ip
        default: op
    bm.unbanip:
        description: Allows you to unban an ip
        default: op
    bm.import:
        description: Allows importing of banned players and ips from Bukkit
        default: op
    bm.kick:
        description: Allows a player to kick another player
        default: op
    bm.update:
        description: Notifies player of a plugin update
        default: op
    bm.mute:
        description: Allows you to mute a player
        default: op
    bm.tempmute:
        description: Allows you to temp mute a player
        default: op
    bm.unmute:
        description: Allows you to unmute a player
        default: op
    bm.warn:
        description: Allows you to warn a player
        default: op
    bm.clear:
        description: Allows you to clear a player's records
        default: op
