# Scheduler intervals in seconds, recommended to leave as default values.
# Setting to 0 disables the scheduler from running.
# Only change if you know what you are doing!
scheduler:
  expiresCheck: 5
  playerBans: 5
  playerMutes: 5
  playerWarnings: 5
  ipBans: 5
  ipRangeBans: 5
  rollbacks: 30
  nameBans: 5
  externalPlayerBans: 5
  externalPlayerMutes: 5
  externalPlayerNotes: 5
  externalIpBans: 5
  saveLastChecked: 60
lastChecked:
  playerMutes: 1776598718
  expiresCheck: 1776598719
  nameBans: 1776598719
  playerBans: 1776598719
  playerWarnings: 1776598719
  externalPlayerNotes: 1776598718
  ipRangeBans: 1776598718
  externalPlayerMutes: 1776598719
  rollbacks: 1776598707
  externalPlayerBans: 1776598719
  externalIpBans: 1776598719
  ipBans: 1776598719
